package view;

import controller.DepartamentoController;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Departamento;

/**
 *
 * @author LUIS
 */
public class FrmDepartamento extends javax.swing.JFrame {
    private DepartamentoController controlador;
    /**
     * Creates new form Departamento
     */
    public FrmDepartamento() {
        initComponents();
        controlador = new DepartamentoController(this);
        txt_codigo.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        cmd_grabar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_dep = new javax.swing.JTable();
        cmd_modificar = new javax.swing.JButton();
        cmd_nuevo = new javax.swing.JButton();
        cmd_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de departamentos");

        jLabel1.setText("Codigo");

        jLabel2.setText("Nombre");

        cmd_grabar.setText("Grabar");
        cmd_grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_grabarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Detalle"));

        tbl_dep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Departamen"
            }
        ));
        tbl_dep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_depMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_dep);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        cmd_modificar.setText("Modificar");
        cmd_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_modificarActionPerformed(evt);
            }
        });

        cmd_nuevo.setText("Nuevo");
        cmd_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_nuevoActionPerformed(evt);
            }
        });

        cmd_eliminar.setText("Eliminar");
        cmd_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(cmd_nuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmd_grabar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmd_modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmd_eliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(txt_codigo)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_grabar)
                    .addComponent(cmd_modificar)
                    .addComponent(cmd_nuevo)
                    .addComponent(cmd_eliminar))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_modificarActionPerformed
        Departamento departamento = new Departamento();
        departamento.setId(Integer.parseInt(txt_codigo.getText()));
        departamento.setNombre(txt_nombre.getText());
        String msn=controlador.modificar(departamento);
        JOptionPane.showMessageDialog(null, msn);
        actualizarTabla();  
    }//GEN-LAST:event_cmd_modificarActionPerformed

    private void cmd_grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_grabarActionPerformed
        Departamento departamento = new Departamento();
        //departamento.setId(Integer.parseInt(txt_codigo.getText()));
        departamento.setNombre(txt_nombre.getText());
        String msn=controlador.insertar(departamento);
        JOptionPane.showMessageDialog(null, msn);
        actualizarTabla();    
    }//GEN-LAST:event_cmd_grabarActionPerformed

    private void cmd_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_nuevoActionPerformed
        int ultimoId = controlador.obtenerUltimoId();
        txt_codigo.setText(String.valueOf(ultimoId + 1));
    }//GEN-LAST:event_cmd_nuevoActionPerformed

    private void tbl_depMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_depMouseClicked
        int filaSeleccionada = tbl_dep.getSelectedRow();

        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1 && filaSeleccionada != -1) {
            // Obtener los datos de la fila seleccionada
            DefaultTableModel modelo = (DefaultTableModel) tbl_dep.getModel();
            String codigo = modelo.getValueAt(filaSeleccionada, 0).toString();
            String departamento = modelo.getValueAt(filaSeleccionada, 1).toString();

            txt_codigo.setText(codigo);
            txt_nombre.setText(departamento);
        }
    }//GEN-LAST:event_tbl_depMouseClicked

    private void cmd_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_eliminarActionPerformed
        Departamento departamento = new Departamento();
        departamento.setId(Integer.parseInt(txt_codigo.getText()));
        departamento.setNombre(txt_nombre.getText());
        String msn=controlador.eliminar(departamento);
        JOptionPane.showMessageDialog(null, msn);
        actualizarTabla();  
    }//GEN-LAST:event_cmd_eliminarActionPerformed
    public JTable getTablaDepartamentos() {
     return tbl_dep;
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        FrmDepartamento frm_dep = new FrmDepartamento();        
        DepartamentoController departamento_c = new DepartamentoController(frm_dep);
        departamento_c.listar(frm_dep.tbl_dep);
        frm_dep.setVisible(true);
        frm_dep.setLocationRelativeTo(frm_dep);
    }
    public void actualizarTabla() {
         controlador.listar(this.tbl_dep);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_eliminar;
    public javax.swing.JButton cmd_grabar;
    public javax.swing.JButton cmd_modificar;
    private javax.swing.JButton cmd_nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbl_dep;
    public javax.swing.JTextField txt_codigo;
    public javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
