/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AlumnoController;
import controller.MatriculaController;
import controller.ModuloController;
import controller.SemestreController;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import model.Matricula;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Usuario
 */
public class FrmMatricula extends javax.swing.JFrame {
    
  private AlumnoController alumnoController;
  private ModuloController moduloController;
  private SemestreController semestreController;
  private MatriculaController matriculaController;
  DefaultTableModel modelo;
  
  /**
   * Creates new form FrmMatricula
   */
  public FrmMatricula() {
    initComponents();
    alumnoController = new AlumnoController();
    moduloController = new ModuloController();
    semestreController = new SemestreController();
    matriculaController = new MatriculaController();
    configurarAutoCompletar();
    
    modelo = new DefaultTableModel();
    modelo.addColumn("DNI");
    modelo.addColumn("MODULO");
    modelo.addColumn("SEMESTRE");
    modelo.addColumn("NOTA");
    
    this.tablaDeDatos.setModel(modelo);
  }

  public void listarBaseDeDatos(){
    List<String[]> listaAlumnoMatriculado = matriculaController.listarAlumnosMatricula();
    for(int i = 0; i<listaAlumnoMatriculado.size(); i++){
      String[] lista = listaAlumnoMatriculado.get(i);
      Object[] data = {lista[0], lista[1], lista[2], lista[3]};
      this.modelo.addRow(data);
    }
  }
  
  public void limpiarTabla(){
    int fila = this.modelo.getRowCount();
    for(int i = fila-1; i>=0; i++){
      modelo.removeRow(i);
    }
  }
  
  private void configurarAutoCompletar() {
      List<String> nombresCompletos = alumnoController.listarNombresYApellidosAlumnos();
      /*
      for(int i = 0; i<nombresCompletos.size(); i++){
        System.out.println(nombresCompletos.get(i));
      }
      */
      AutoCompleteDecorator.decorate(txt_alumno, nombresCompletos, false);
      
      List<String> modulos = moduloController.listarNombres();
      AutoCompleteDecorator.decorate(txt_modulos, modulos, false);
      
      List<String> detallesSemestre = semestreController.listarDetalle();
      AutoCompleteDecorator.decorate(txt_semestre, detallesSemestre, false);
    }
  
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    txt_alumno = new javax.swing.JTextField();
    txt_modulos = new javax.swing.JTextField();
    txt_semestre = new javax.swing.JTextField();
    txt_nota = new javax.swing.JTextField();
    txt_dni = new javax.swing.JTextField();
    txt_moduloId = new javax.swing.JTextField();
    txt_semestreId = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaDeDatos = new javax.swing.JTable();
    jButton2 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setText("ESTUDIANTE");

    jLabel2.setText("MODULO");

    jLabel3.setText("SEMESTRE");

    jLabel4.setText("NOTA");

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("PROCESO DE MATRICULA");

    txt_alumno.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txt_alumnoActionPerformed(evt);
      }
    });

    txt_modulos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txt_modulosActionPerformed(evt);
      }
    });

    txt_semestre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txt_semestreActionPerformed(evt);
      }
    });

    txt_dni.setEditable(false);

    txt_moduloId.setEditable(false);

    txt_semestreId.setEditable(false);

    jButton1.setText("GRABAR");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    tablaDeDatos.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(tablaDeDatos);

    jButton2.setText("listarTodo");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(txt_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txt_dni, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(txt_modulos, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txt_moduloId))
          .addGroup(layout.createSequentialGroup()
            .addComponent(txt_semestre, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txt_semestreId))
          .addGroup(layout.createSequentialGroup()
            .addComponent(txt_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))))
      .addGroup(layout.createSequentialGroup()
        .addGap(50, 50, 50)
        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(27, 27, 27)
        .addComponent(jButton2)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
          .addComponent(txt_alumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(txt_modulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txt_moduloId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(txt_semestre)
            .addComponent(txt_semestreId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(txt_nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton1)
          .addComponent(jButton2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txt_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alumnoActionPerformed
    Map<String, String> mapaNombresDni = alumnoController.obtenerMapaNombresDni();
    String nombreSeleccionado = txt_alumno.getText();
    String dni = mapaNombresDni.get(nombreSeleccionado);
    txt_dni.setText(dni != null ? dni : "");
  }//GEN-LAST:event_txt_alumnoActionPerformed

  private void txt_modulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_modulosActionPerformed
    //moduloController
    Map<String, Integer> mapaNombresId = moduloController.obtenerMapaNombresId();
    String moduloSeleccionado = txt_modulos.getText();
    int dni = mapaNombresId.get(moduloSeleccionado);
    txt_moduloId.setText(dni > 0 ? dni+"" : "");
  }//GEN-LAST:event_txt_modulosActionPerformed

  private void txt_semestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_semestreActionPerformed
    Map<String, String> mapaDetalleId = semestreController.convertir_a_mapa();
    String detalleSeleccionado = txt_semestre.getText();
    String id = mapaDetalleId.get(detalleSeleccionado);
    txt_semestreId.setText(id  != null ? id  : "");
  }//GEN-LAST:event_txt_semestreActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

  }//GEN-LAST:event_jButton2ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String dniAlumno = txt_dni.getText();
    String idModulo = txt_moduloId.getText();
    String idSemestre = txt_semestreId.getText();
    String nota = txt_nota.getText();
    
    Matricula matri = new Matricula();
    matri.setDni(dniAlumno);
    matri.setIdModulo(idModulo);
    matri.setIdSemestre(idSemestre);
    matri.setNota(Float.parseFloat(nota));
    
    this.matriculaController.insertarAlumnosMatricula(matri);
    System.out.println("datos almacenados correctamente");
    
    this.limpiarTabla();
    this.listarBaseDeDatos();
  }//GEN-LAST:event_jButton1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrmMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrmMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrmMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrmMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FrmMatricula().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tablaDeDatos;
  private javax.swing.JTextField txt_alumno;
  private javax.swing.JTextField txt_dni;
  private javax.swing.JTextField txt_moduloId;
  private javax.swing.JTextField txt_modulos;
  private javax.swing.JTextField txt_nota;
  private javax.swing.JTextField txt_semestre;
  private javax.swing.JTextField txt_semestreId;
  // End of variables declaration//GEN-END:variables
}
